services:
  cmsingbox:
    build:
      context: .
      args:
        VERSION: ${CMSINGBOX_VERSION:-latest}
        LICENSE_PUBLIC_KEY: ${CMSINGBOX_LICENSE_PUBLIC_KEY:-EwFgPIqxKUjPY45bIUHviX4fyZLAGoww6q5QJs9fKcE=}
        FREE_SUBSCRIPTION_LIMIT: ${CMSINGBOX_FREE_SUBSCRIPTION_LIMIT:-1}
    container_name: cmsingbox
    restart: unless-stopped
    privileged: true
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Shanghai
      - CMSINGBOX_LICENSE_PUBLIC_KEY=${CMSINGBOX_LICENSE_PUBLIC_KEY:-EwFgPIqxKUjPY45bIUHviX4fyZLAGoww6q5QJs9fKcE=}
    networks:
      cmsingbox_lan:
        ipv4_address: ${CMSINGBOX_IP:?请设置 CMSINGBOX_IP}

networks:
  cmsingbox_lan:
    driver: macvlan
    driver_opts:
      parent: ${CMSINGBOX_PARENT:?请设置 CMSINGBOX_PARENT}
    ipam:
      config:
        - subnet: ${CMSINGBOX_SUBNET:?请设置 CMSINGBOX_SUBNET}
          gateway: ${CMSINGBOX_GATEWAY:?请设置 CMSINGBOX_GATEWAY}
