services:
  cmsingbox:
    image: darkver8/cmsingbox:latest
    container_name: cmsingbox-fnos
    restart: unless-stopped
    privileged: true
    environment:
      TZ: Asia/Shanghai
    volumes:
      - "${TRIM_PKGVAR}/data:/data"
    networks:
      cmsingbox_lan:
        ipv4_address: "${wizard_cmsingbox_ip}"

networks:
  cmsingbox_lan:
    driver: macvlan
    driver_opts:
      parent: "${wizard_parent_interface}"
    ipam:
      config:
        - subnet: "${wizard_subnet}"
          gateway: "${wizard_gateway}"
